import { MENU_IMAGES } from "./image-config"

export const menuData = {
  maharashtrian: [
    {
      id: "poha",
      name: "पोहे",
      englishName: "Poha",
      price: "₹50",
      description:
        "Flattened rice flakes tempered with mustard seeds, curry leaves, onions, and garnished with fresh coriander and grated coconut.",
      image: MENU_IMAGES.maharashtrianBreakfast.poha,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "upit",
      name: "उपीट",
      englishName: "Upit",
      price: "₹50",
      description:
        "A savory semolina dish cooked with vegetables and spices, a staple breakfast in Maharashtrian homes.",
      image: MENU_IMAGES.maharashtrianBreakfast.upit,
      isVeg: true,
    },
    {
      id: "sheera",
      name: "शिरा",
      englishName: "Sheera",
      price: "₹60",
      description: "Sweet semolina pudding made with ghee, sugar, and cardamom, often garnished with nuts and raisins.",
      image: MENU_IMAGES.maharashtrianBreakfast.sheera,
      isVeg: true,
    },
    {
      id: "misal-pav",
      name: "मिसळ पाव",
      englishName: "Misal Pav",
      price: "₹80",
      description:
        "Spicy sprouted lentil curry topped with farsan (crunchy mixture), onions, and coriander, served with pav (bread rolls).",
      image: MENU_IMAGES.maharashtrianBreakfast.misalPav,
      isVeg: true,
      isSpicy: true,
      isPopular: true,
    },
    {
      id: "vada-pav",
      name: "वडा पाव",
      englishName: "Vada Pav",
      price: "₹30",
      description: "The iconic Mumbai street food - spicy potato fritter sandwiched in a pav with chutneys.",
      image: MENU_IMAGES.maharashtrianBreakfast.vadaPav,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "cut-vada",
      name: "कट वडा",
      englishName: "Cut Vada",
      price: "₹60",
      description: "Crispy lentil fritters cut into pieces, topped with spicy gravy, chutneys, and garnishes.",
      image: MENU_IMAGES.maharashtrianBreakfast.cutVada,
      isVeg: true,
    },
    {
      id: "kothimbir-vadi",
      name: "कोथिंबीर वडी",
      englishName: "Kothimbir Vadi",
      price: "₹60",
      description: "Steamed and then fried coriander cakes made with gram flour, spices, and fresh coriander leaves.",
      image: MENU_IMAGES.maharashtrianBreakfast.kothimbirVadi,
      isVeg: true,
    },
    {
      id: "aloo-vadi",
      name: "आळूवडी",
      englishName: "Aloo Vadi",
      price: "₹60",
      description: "Colocasia leaves smeared with gram flour paste, rolled, steamed and then fried to perfection.",
      image: MENU_IMAGES.maharashtrianBreakfast.alooVadi,
      isVeg: true,
    },
    {
      id: "nashta-thali",
      name: "नाष्टा थाली",
      englishName: "Breakfast Thali",
      price: "₹50",
      description:
        "A complete breakfast platter with Kat-Vada, Poha, and Upit, offering a taste of authentic Maharashtrian breakfast.",
      image: MENU_IMAGES.maharashtrianBreakfast.nashtaThali,
      isVeg: true,
    },
    {
      id: "sabudana-khichdi-nashta",
      name: "साबूदाणा खिचडी",
      englishName: "Sabudana Khichdi",
      price: "₹60",
      description:
        "Light and flavorful dish made with tapioca pearls, peanuts, and potatoes, seasoned with cumin and green chilies.",
      image: MENU_IMAGES.maharashtrianBreakfast.poha,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "sabudana-vada-nashta",
      name: "साबूदाणा वडा",
      englishName: "Sabudana Vada",
      price: "₹70",
      description: "Crispy fritters made with soaked tapioca pearls, peanuts, potatoes, and spices.",
      image: MENU_IMAGES.maharashtrianBreakfast.upit,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "bhakri",
      name: "भाकरी",
      englishName: "Bhakri",
      price: "₹30",
      description: "Rustic flatbread made from jowar (sorghum) or bajra (pearl millet) flour.",
      image: MENU_IMAGES.maharashtrianBreakfast.misalPav,
      isVeg: true,
    },
    {
      id: "puri-bhaji",
      name: "पुरी भाजी",
      englishName: "Puri Bhaji",
      price: "₹80",
      description: "Deep-fried bread served with spicy potato curry, a popular comfort food.",
      image: MENU_IMAGES.maharashtrianBreakfast.cutVada,
      isVeg: true,
    },
    {
      id: "baigan-bharta",
      name: "बैगन भर्ता",
      englishName: "Baigan Bharta",
      price: "₹100",
      description: "Roasted eggplant mashed and cooked with onions, tomatoes, and spices.",
      image: MENU_IMAGES.maharashtrianBreakfast.kothimbirVadi,
      isVeg: true,
      isSpicy: true,
    },
  ],

  upvas: [
    {
      id: "sabudana-vada",
      name: "साबूदाणा वडा",
      englishName: "Sabudana Vada",
      price: "₹60",
      description:
        "Crispy fritters made with soaked tapioca pearls, peanuts, potatoes, and spices, perfect for fasting days.",
      image: MENU_IMAGES.upvasSpecial.sabudanaVada,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "sabudana-khichdi",
      name: "साबूदाणा खिचडी",
      englishName: "Sabudana Khichdi",
      price: "₹50",
      description:
        "A light and flavorful dish made with tapioca pearls, peanuts, and potatoes, seasoned with cumin and green chilies.",
      image: MENU_IMAGES.upvasSpecial.sabudanaKhichdi,
      isVeg: true,
    },
    {
      id: "sabudana-kachori",
      name: "साबूदाणा कचोरी",
      englishName: "Sabudana Kachori",
      price: "₹50",
      description:
        "Deep-fried pastry filled with a spiced mixture of tapioca pearls and potatoes, a delicious fasting snack.",
      image: MENU_IMAGES.upvasSpecial.sabudanaKachori,
      isVeg: true,
    },
    {
      id: "bhagar-rice",
      name: "भगर भात",
      englishName: "Bhagar Rice",
      price: "₹60",
      description: "A fasting dish made with barnyard millet, peanuts, and minimal spices, light yet satisfying.",
      image: MENU_IMAGES.upvasSpecial.bhagarRice,
      isVeg: true,
    },
    {
      id: "farali-thali",
      name: "फराळी थाळी",
      englishName: "Fasting Thali",
      price: "₹120",
      description:
        "A complete fasting meal with various permitted dishes like sabudana khichdi, potato sabzi, and more.",
      image: MENU_IMAGES.upvasSpecial.faraliThali,
      isVeg: true,
    },
  ],

  southIndian: [
    {
      id: "idli-sambar",
      name: "इडली सांबर",
      englishName: "Idli Sambar",
      price: "₹60",
      description: "Soft, steamed rice cakes served with spicy lentil soup and coconut chutney.",
      image: MENU_IMAGES.southIndian.idliSambar,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "mix-medu-vada",
      name: "मिक्स मेदुवडा",
      englishName: "Mix Medu Vada",
      price: "₹70",
      description: "Crispy, savory doughnut-shaped fritters made from mixed lentils, served with sambar and chutney.",
      image: MENU_IMAGES.southIndian.mixMeduVada,
      isVeg: true,
    },
    {
      id: "medu-vada",
      name: "मेदुवडा",
      englishName: "Medu Vada",
      price: "₹80",
      description: "Traditional South Indian fritters made from urad dal, crispy outside and soft inside.",
      image: MENU_IMAGES.southIndian.meduVada,
      isVeg: true,
    },
    {
      id: "batata-vada",
      name: "बटाटा वडा",
      englishName: "Batata Vada",
      price: "₹60",
      description: "Spiced potato fritters served with coconut chutney and sambar.",
      image: MENU_IMAGES.southIndian.batataVada,
      isVeg: true,
    },
    {
      id: "plain-dosa",
      name: "प्लेन डोसा",
      englishName: "Plain Dosa",
      price: "₹70",
      description: "Thin, crispy crepe made from fermented rice and lentil batter, served with sambar and chutney.",
      image: MENU_IMAGES.southIndian.plainDosa,
      isVeg: true,
    },
    {
      id: "masala-dosa",
      name: "मसाला डोसा",
      englishName: "Masala Dosa",
      price: "₹90",
      description: "Crispy rice crepe filled with spiced potato filling, served with sambar and coconut chutney.",
      image: MENU_IMAGES.southIndian.masalaDosa,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "paper-plain-dosa",
      name: "पेपर प्लेन डोसा",
      englishName: "Paper Plain Dosa",
      price: "₹120",
      description: "Extra thin and crispy dosa spread wide like paper, served with sambar and chutney.",
      image: MENU_IMAGES.southIndian.paperPlainDosa,
      isVeg: true,
    },
    {
      id: "paper-masala-dosa",
      name: "पेपर मसाला डोसा",
      englishName: "Paper Masala Dosa",
      price: "₹140",
      description: "Extra thin and crispy dosa filled with spiced potato filling, a South Indian delicacy.",
      image: MENU_IMAGES.southIndian.paperMasalaDosa,
      isVeg: true,
    },
    {
      id: "mysore-plain-dosa",
      name: "मैसूर प्लेन डोसा",
      englishName: "Mysore Plain Dosa",
      price: "₹100",
      description: "Dosa smeared with spicy red chutney on the inside, served with sambar and coconut chutney.",
      image: MENU_IMAGES.southIndian.mysorePlainDosa,
      isVeg: true,
      isSpicy: true,
    },
  ],

  soup: [
    {
      id: "veg-manchow-soup",
      name: "व्हेज मंचाव सूप",
      englishName: "Veg Manchow Soup",
      price: "₹80",
      description: "Hot and spicy Indo-Chinese soup with finely chopped vegetables and crispy noodles.",
      image: MENU_IMAGES.soups.vegManchowSoup,
      isVeg: true,
      isSpicy: true,
    },
    {
      id: "veg-hot-sour-soup",
      name: "व्हेज हॉट अंड सॉर सूप",
      englishName: "Veg Hot & Sour Soup",
      price: "₹70",
      description: "Tangy and spicy soup with vegetables, bamboo shoots, and tofu in a flavorful broth.",
      image: MENU_IMAGES.soups.vegHotSourSoup,
      isVeg: true,
      isSpicy: true,
    },
    {
      id: "veg-sweet-corn-soup",
      name: "व्हेज स्वीट कॉर्न सूप",
      englishName: "Veg Sweet Corn Soup",
      price: "₹80",
      description: "Mild and creamy soup made with sweet corn kernels and finely chopped vegetables.",
      image: MENU_IMAGES.soups.vegSweetCornSoup,
      isVeg: true,
    },
    {
      id: "veg-tomato-soup",
      name: "व्हेज टोमॅटो सूप",
      englishName: "Veg Tomato Soup",
      price: "₹70",
      description: "Classic tomato soup made with fresh tomatoes, herbs, and a touch of cream.",
      image: MENU_IMAGES.soups.vegTomatoSoup,
      isVeg: true,
    },
  ],

  mainCourse: [
    {
      id: "veg-kolhapuri",
      name: "व्हेज कोल्हापुरी",
      englishName: "Veg Kolhapuri",
      price: "₹150",
      description: "Vegetables in an intensely spicy gravy made with the famous Kolhapuri masala.",
      image: MENU_IMAGES.mainCourse.vegKolhapuri,
      isVeg: true,
      isSpicy: true,
      isPopular: true,
    },
    {
      id: "veg-kadhai",
      name: "व्हेज कढाई",
      englishName: "Veg Kadhai",
      price: "₹140",
      description: "Vegetables cooked in a spicy, tangy gravy with bell peppers and kadhai spices.",
      image: MENU_IMAGES.mainCourse.vegKadhai,
      isVeg: true,
      isSpicy: true,
    },
    {
      id: "mix-veg",
      name: "मिक्स व्हेज",
      englishName: "Mix Veg",
      price: "₹130",
      description: "Assorted vegetables cooked in a rich, spiced gravy.",
      image: MENU_IMAGES.mainCourse.mixVeg,
      isVeg: true,
    },
    {
      id: "malai-kofta",
      name: "मलाई कोफ्ता",
      englishName: "Malai Kofta",
      price: "₹170",
      description: "Soft, creamy dumplings made with paneer and potatoes, served in a rich gravy.",
      image: MENU_IMAGES.mainCourse.malaiKofta,
      isVeg: true,
    },
    {
      id: "palak-paneer",
      name: "पालक पनीर",
      englishName: "Palak Paneer",
      price: "₹160",
      description: "Cottage cheese cubes in a smooth, creamy spinach gravy.",
      image: MENU_IMAGES.mainCourse.palakPaneer,
      isVeg: true,
    },
    {
      id: "paneer-butter-masala",
      name: "पनीर बटर मसाला",
      englishName: "Paneer Butter Masala",
      price: "₹170",
      description: "Cottage cheese cubes in a rich, creamy tomato gravy with butter.",
      image: MENU_IMAGES.mainCourse.paneerButterMasala,
      isVeg: true,
      isPopular: true,
    },
  ],

  nonVeg: [
    {
      id: "chicken-curry",
      name: "चिकन करी",
      englishName: "Chicken Curry",
      price: "₹200",
      description: "Tender chicken pieces cooked in a flavorful, spiced curry gravy.",
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Curry",
      isVeg: false,
      isPopular: true,
      isSpicy: true,
    },
    {
      id: "chicken-fry",
      name: "चिकन फ्राय",
      englishName: "Chicken Fry",
      price: "₹220",
      description: "Crispy fried chicken pieces marinated with spices and herbs.",
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Fry",
      isVeg: false,
      isPopular: true,
    },
    {
      id: "mutton-bhakri",
      name: "मटण भाकरी",
      englishName: "Mutton Bhakri",
      price: "₹280",
      description: "Traditional mutton curry served with rustic bhakri (millet flatbread).",
      image: "/placeholder.svg?height=400&width=600&text=Mutton+Bhakri",
      isVeg: false,
      isSpicy: true,
      isPopular: true,
    },
    {
      id: "fish-curry",
      name: "फिश करी",
      englishName: "Fish Curry",
      price: "₹220",
      description: "Fresh fish cooked in a tangy, spicy coconut-based curry.",
      image: "/placeholder.svg?height=400&width=600&text=Fish+Curry",
      isVeg: false,
      isSpicy: true,
    },
    {
      id: "fish-fry",
      name: "फिश फ्राय",
      englishName: "Fish Fry",
      price: "₹240",
      description: "Crispy fried fish marinated with coastal spices.",
      image: "/placeholder.svg?height=400&width=600&text=Fish+Fry",
      isVeg: false,
      isPopular: true,
    },
    {
      id: "egg-bhurji",
      name: "एग भुर्जी",
      englishName: "Egg Bhurji",
      price: "₹80",
      description: "Scrambled eggs cooked with onions, tomatoes, and spices.",
      image: "/placeholder.svg?height=400&width=600&text=Egg+Bhurji",
      isVeg: false,
    },
  ],

  biryani: [
    {
      id: "chicken-biryani",
      name: "चिकन बिर्याणी",
      englishName: "Chicken Biryani",
      price: "₹220",
      description: "Aromatic basmati rice layered with tender chicken pieces and traditional spices. Our Bestseller!",
      image: "/placeholder.svg?height=400&width=600&text=Chicken+Biryani",
      isVeg: false,
      isPopular: true,
    },
    {
      id: "paneer-biryani",
      name: "पनीर बिर्याणी",
      englishName: "Paneer Biryani",
      price: "₹190",
      description: "Premium basmati rice layered with marinated paneer cubes and exquisite spices. Most Loved!",
      image: "/placeholder.svg?height=400&width=600&text=Paneer+Biryani",
      isVeg: true,
      isPopular: true,
    },
    {
      id: "veg-biryani",
      name: "व्हेज बिर्याणी",
      englishName: "Veg Biryani",
      price: "₹180",
      description: "Fragrant basmati rice layered with mixed vegetables and aromatic spices.",
      image: MENU_IMAGES.rice.vegBiryani,
      isVeg: true,
      isPopular: true,
    },
  ],

  thali: [
    {
      id: "maharashtrian-thali",
      name: "महाराष्ट्रीयन थाळी",
      englishName: "Maharashtrian Thali",
      price: "₹180",
      description: "Complete traditional Maharashtrian meal with rice, chapati, dal, sabzi, and sweet.",
      image: MENU_IMAGES.thali.maharashtrianThali,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "south-indian-thali",
      name: "साउथ इंडियन थाळी",
      englishName: "South Indian Thali",
      price: "₹160",
      description: "Authentic South Indian platter with rice, sambar, rasam, and assorted dishes.",
      image: MENU_IMAGES.thali.southIndianThali,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "jain-thali",
      name: "जैन थाळी",
      englishName: "Jain Thali",
      price: "₹170",
      description: "Special Jain meal prepared without onion and garlic, with traditional accompaniments.",
      image: MENU_IMAGES.thali.jainThali,
      isVeg: true,
    },
  ],

  mainCourseMaharashtrian: [
    {
      id: "pithala",
      name: "पिठलं",
      englishName: "Pithala",
      price: "₹80",
      description:
        "Traditional Maharashtrian dish made with gram flour, spices, and herbs, similar to a thick savory porridge.",
      image: MENU_IMAGES.maharashtrianMainCourse.pithala,
      isVeg: true,
    },
    {
      id: "bharla-vanga",
      name: "भरल वांग",
      englishName: "Bharla Vanga",
      price: "₹80",
      description: "Stuffed eggplants cooked with a spicy peanut and coconut filling, a Maharashtrian delicacy.",
      image: MENU_IMAGES.maharashtrianMainCourse.bharlaVanga,
      isVeg: true,
      isSpicy: true,
    },
    {
      id: "puri-bhaji",
      name: "पुरी भाजी",
      englishName: "Puri Bhaji",
      price: "₹90",
      description: "Deep-fried bread served with spicy potato curry, a popular comfort food.",
      image: MENU_IMAGES.maharashtrianMainCourse.puriBhaji,
      isVeg: true,
    },
    {
      id: "matki-usal",
      name: "मटकी उसळ",
      englishName: "Matki Usal",
      price: "₹80",
      description: "Sprouted moth beans curry cooked with onions, tomatoes, and traditional spices.",
      image: MENU_IMAGES.maharashtrianMainCourse.matkiUsal,
      isVeg: true,
    },
    {
      id: "bhakri-main",
      name: "भाकरी",
      englishName: "Bhakri",
      price: "₹30",
      description:
        "Rustic flatbread made from jowar (sorghum) or bajra (pearl millet) flour, a staple in rural Maharashtra.",
      image: MENU_IMAGES.maharashtrianMainCourse.bhakri,
      isVeg: true,
    },
    {
      id: "aamti-bhat",
      name: "आमटी भात",
      englishName: "Aamti Bhat",
      price: "₹80",
      description: "Tangy lentil curry served with steamed rice, a comfort food in Maharashtrian homes.",
      image: MENU_IMAGES.maharashtrianMainCourse.aamtiBhat,
      isVeg: true,
    },
  ],

  beverages: [
    {
      id: "tea",
      name: "चहा",
      englishName: "Tea",
      price: "₹20",
      description: "Hot, refreshing Indian chai.",
      image: MENU_IMAGES.hotDrinks.tea,
      isVeg: true,
    },
    {
      id: "filter-coffee",
      name: "फिल्टर कॉफी",
      englishName: "Filter Coffee",
      price: "₹30",
      description: "South Indian style filter coffee.",
      image: MENU_IMAGES.hotDrinks.filterCoffee,
      isVeg: true,
    },
    {
      id: "cold-coffee",
      name: "कोल्ड कॉफी",
      englishName: "Cold Coffee",
      price: "₹60",
      description: "Refreshing cold coffee with ice cream.",
      image: MENU_IMAGES.coldDrinks.coldCoffee,
      isVeg: true,
      isPopular: true,
    },
    {
      id: "lassi",
      name: "लस्सी",
      englishName: "Lassi",
      price: "₹50",
      description: "Traditional yogurt-based drink.",
      image: MENU_IMAGES.coldDrinks.lassi,
      isVeg: true,
    },
  ],

  rice: [
    {
      id: "veg-pulao",
      name: "व्हेज पुलाव",
      englishName: "Veg Pulao",
      price: "₹150",
      description: "Fragrant rice cooked with mixed vegetables and aromatic spices.",
      image: MENU_IMAGES.rice.vegPulao,
      isVeg: true,
    },
    {
      id: "jeera-rice",
      name: "जीरा राईस",
      englishName: "Jeera Rice",
      price: "₹80",
      description: "Basmati rice tempered with cumin seeds and garnished with coriander.",
      image: MENU_IMAGES.rice.jeeraRice,
      isVeg: true,
    },
    {
      id: "curd-rice",
      name: "कर्ड राईस",
      englishName: "Curd Rice",
      price: "₹120",
      description:
        "Soft rice mixed with yogurt, tempered with mustard seeds and curry leaves, a South Indian comfort food.",
      image: MENU_IMAGES.rice.curdRice,
      isVeg: true,
    },
  ],

  breads: [
    {
      id: "chapati",
      name: "चपाती",
      englishName: "Chapati",
      price: "₹12",
      description: "Thin, unleavened flatbread made from whole wheat flour, a staple in Indian meals.",
      image: MENU_IMAGES.breads.chapati,
      isVeg: true,
    },
    {
      id: "butter-naan",
      name: "बटर नान",
      englishName: "Butter Naan",
      price: "₹40",
      description: "Leavened flatbread cooked in a tandoor and brushed with butter.",
      image: MENU_IMAGES.breads.butterNaan,
      isVeg: true,
    },
    {
      id: "garlic-naan",
      name: "लसूण नान",
      englishName: "Garlic Naan",
      price: "₹50",
      description: "Leavened flatbread topped with minced garlic and cooked in a tandoor.",
      image: MENU_IMAGES.breads.garlicNaan,
      isVeg: true,
    },
    {
      id: "laccha-paratha",
      name: "लच्छा पराठा",
      englishName: "Laccha Paratha",
      price: "₹40",
      description: "Layered, flaky flatbread made from whole wheat flour.",
      image: MENU_IMAGES.breads.lacchaParatha,
      isVeg: true,
    },
  ],
}
